name: NeoIoTest-manual-trigger

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'The operating system to run the tests on'
        required: True
        default: 'ubuntu-latest'
        type: choice
        options:
          - macos-latest
          - windows-latest

jobs:
  call-iotests:
    uses: ./.github/workflows/io-test.yml
    with:
      os: ${{ inputs.os }}